# Generated by Django 4.2.9 on 2024-02-13 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('type_of_user', models.CharField(choices=[('renter', 'Renter'), ('landlord', 'Landlord')], max_length=8)),
                ('id_proof', models.CharField(max_length=255, null=True)),
                ('date_of_birth', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_type', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('property_images', models.TextField()),
                ('property_details', models.TextField()),
                ('renting_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('services_subscription_active', models.BooleanField()),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.persons')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.properties')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.persons')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_text', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.properties')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.persons')),
            ],
        ),
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('rental_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tenure', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=7)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_payment_date', models.DateField()),
                ('last_payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_payment_date', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.properties')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.persons')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_of_payment', models.CharField(max_length=50)),
                ('success_status', models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed')], max_length=7)),
                ('bank', models.CharField(max_length=255)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.rentals')),
            ],
        ),
    ]
